### PR TITLE
upgrade to ember-cli 3.20 and other dependencies

### PR DESCRIPTION
**Pull request by nickschot**
~~Makes #74 unnecessary.~~

~~Ideally we need ember-showdown-prism to be released with https://github.com/empress/ember-showdown-prism/pull/4 so we dont have to rely on the branch version.~~ done, PR updated.

~~Needs #76 to build properly.~~ updated

Edit: This was originally including #77 but @mansona split that out into a separate PR 👍

### CODE REVIEW

**Comment by nickschot** [comment]
Not entirely sure why netlify's build is failing with the weird ember-data error. Might be a cache thing. I don't have the power to restart the build.

**Comment by nickschot** [comment]
So indeed, tests work, netlify needs its cache to be deleted.

**Comment by mansona** [comment]
so... I had to rebuild the Netlify because it failed originally, but now it is passing but throwing a strange error in the build for some of the pages 🤔  `TypeError: Cannot read property 'rest' of undefined` any ideas? https://app.netlify.com/sites/empress-blog-ember-template/deploys/5f3aa5d8ad43c451b3a78e84

**Comment by nickschot** [comment]
Yes this is what I made the other PR for in the showdown-prism repo. This error happens when you pass a language to the markdown codeblock which isn't supported by prism or it's config. I replaced the "sh" occurrences with bash already, maybe I missed some more?

**Review by mansona — APPROVED** [review]
looks good 👍

**Pull request merged**
