### PR TITLE
[WIP]- Implement Author Page design

### PR DESCRIPTION
**Pull request by claeusdev**
Fixes https://github.com/ember-learn/empress-blog-ember-template/issues/68

### CODE REVIEW

**Comment by mansona** [comment]
Hey 👋  thanks for making a start on this 🎉 

Can I just ask, which author are you using to test your implementation? It looks like not all of the authors have the same sorts of data 🤔  as you can see https://deploy-preview-79--empress-blog-ember-template.netlify.app/author/chris/ has a lot of extra stuff compared to https://deploy-preview-79--empress-blog-ember-template.netlify.app/author/kenneth-larsen/ 

I know we don't have images in the design but I wonder if we should add them or if we should just not implement them if they are implemented in the data 🤔  what do you think @claeusdev?

**Comment by claeusdev** [comment]
> Hey 👋 thanks for making a start on this 🎉
> 
> Can I just ask, which author are you using to test your implementation? It looks like not all of the authors have the same sorts of data 🤔 as you can see https://deploy-preview-79--empress-blog-ember-template.netlify.app/author/chris/ has a lot of extra stuff compared to https://deploy-preview-79--empress-blog-ember-template.netlify.app/author/kenneth-larsen/
> 
> I know we don't have images in the design but I wonder if we should add them or if we should just not implement them if they are implemented in the data 🤔 what do you think @claeusdev?

Ah yes, I was using Kenneth's profile to test my implementation. 
Honestly, I think we should implement them or we could align the data to have the additional info for all authors. On second thought, I think it would be better to implement this only for this issue and then complete the data and display it in another issue.

**Comment by mansona** [comment]
So if you think it's best to add an implementation that works with an image then you can go ahead with that 👍  don't worry about updating the data because that will need to be a completely different PR anyway because the real data is in a different repo (this repo is just the template)

The best thing to do is to develop things as if all of the data is optional (apart from maybe the name 😂 ) and that way it doesn't matter if some users are missing some of the data, it will still look good 💪

**Comment by mansona** [comment]
I will also bring up the need for an update to the design at the weekly meeting 👍  so if you don't get this updated this week you might have an updated design later

**Comment by claeusdev** [comment]
oh, that's awesome. Quick one though, do we include the sidebar as well in this implementation?

**Comment by mansona** [comment]
oh yes I forgot about that part of the question 🙈  yes the sidebar should be there, but to do that you just need to remove the implementation of `showSidebar` here https://github.com/ember-learn/empress-blog-ember-template/blob/master/addon/components/tag-sidebar.js#L7

**Comment by mansona** [comment]
Hey @claeusdev I'm so sorry for the very long delay, we actually went through some iterations on the design side to try and figure out what to do with this PR when the author has an image 🤔  (for example: https://deploy-preview-79--empress-blog-ember-template.netlify.app/author/chris/ ) 

We got the designs merged last week and here is an indication of what it should look like: https://share.goabstract.com/0589f9f1-7762-4f2f-826a-1104f0669a18

The size of the image is actually on a grid that you can see more information about here: https://ember-styleguide.netlify.app/concepts/layout/

Are you able to take a look at this? I know it has been a long time 🙈  If you are busy just let me know and I can take over from your PR and finish it off 👍

**Comment by claeusdev** [comment]
Oh yeah, @mansona i will take a look at this over the weekend

**Pull request closed without merging**
